### ISSUE TITLE
New solution isn't updated

### ISSUE THREAD

**Issue by trungnguyencs** [QasimWani/LeetHub#54]
Somehow for problems that were already submitted to Github by Leethub before, when I redo them, the new solutions are not pushed to Github anymore.
I have tried to reload Leetcode after each submission but still didn't get it working.

I.e.:
I have just submitted a new solution to this problem:
![image](https://user-images.githubusercontent.com/32110646/102385088-46241400-3f82-11eb-92b3-63cf860376ec.png)
But the last solution on Github was still the one that I submitted on Dec 7:
![image](https://user-images.githubusercontent.com/32110646/102385309-8c797300-3f82-11eb-9972-342cc91b2794.png)

**Comment by QasimWani** [comment]
thanks for bringing it up. Turns out the only thing being updated was your readme (see your commits), and not the actual code. This is because the sequence of XHR requests had an incorrect logical filter, causing this issue. 
I've fixed it now, and submitted to Chrome Webstore.
So, expect this fix to take another 24hrs-ish before you can see it being reflected on LeetHub.

**Comment by QasimWani** [comment]
@trungnguyencs could you confirm if this fixed it for you? (reload the extension, make sure it's v.1.1)
thanks for using leethub :D

**Comment by Ebad8931** [comment]
Even though this issue is closed, I am still getting the same issue, where new submissions on Leetcode are not reflected in the GitHub repo. I have tried reloading Leetcode and also browsing to other questions and then coming back to this one. The Github repo has the very first submission on Leetcode.

![image](https://user-images.githubusercontent.com/32314759/119232630-db0fd800-baf3-11eb-83bd-6e06082cd07b.png)

Here is the history of commits on my Github repo
![image](https://user-images.githubusercontent.com/32314759/119232768-6d17e080-baf4-11eb-8c41-4415a64ce4a6.png)

**Comment by QasimWani** [comment]
can u change ur code (perhaps add a space/newline somewhere) on leetcode.com and resubmit it then?

**Comment by K02D** [comment]
I'm experiencing the same problem even though my second submission has completely different code

**Comment by DarshanGowda0** [comment]
Yep, started using this plugin today and came searching to report the same issue!
Can confirm I have two different code snippets, one iterative and one recursive solution, the plugin doesn't pickup the latest submission!

**Comment by YeonCheolGit** [comment]
I've still struggled with this issue. I submitted changed code but still doesn't work.

**Comment by krishnansr** [comment]
The browser I was using was brave as well, I tried whitelisting leetcode through the browser's adblocker and a widget I had (uBlock) and it worked like a charm after that

**Comment by Pragati1419** [comment]
Leethub not syncing the geeksforgeeks codes on GitHub while Leetcode  codes are updating in repo .please help to solve this issue

**Comment by codingpanda0112** [comment]
@QasimWani Leethub not syncing the geeksforgeeks codes on GitHub

**Comment by babson89** [comment]
Leethub nit syncing the Leetcode codes on Github. Can you help me with that ?

**Comment by nabanitadewan** [comment]
@QasimWani Leethub is not syncing leetcode on Github. I have removed adBlocker as well for leetcode.

**Comment by being-nitin** [comment]
leetcode has updated its interface and after updation the extension is not working.

**Comment by akshay117** [comment]
Leethub is no longer syncing to GitHub after leetcode updated their interface

**Comment by tIcers** [comment]
I have a same problem. I am using brave browser, and my code/solution can not be pushed to my GitHub.

**Comment by harshalyeole** [comment]
Not working for me either, any alternative?

**Comment by akshay117** [comment]
> Not working for me either, any alternative?

Yes, Change the leetcode to use old version.

**Comment by JetechNY** [comment]
Leethub not working. no new uploads

**Comment by rhythm10** [comment]
Leethub still not working even after resetting Leetcode to an older Version.
Why it shows in the description regarding GFG code also able to push to Git, that is not even updated in Extension UI or anywhere

**Comment by avi02iter** [comment]
WHY LEETHUB IS NOT WORKING AND COMMITING TO MY GITHUB

**Comment by ayasahmad7655** [comment]
Leethub not Working >>

**Comment by sachin9998** [comment]
Leethub is not working on Chrome, Mac OS M1

**Comment by floatingnahid22** [comment]
Leethub not working!! I have removed it and again added in my browser and then setup with my github repository but still it not working. What to do?

**Comment by heyoni** [comment]
It wasn't just about me. I'm having the same problem. I'm using M1 and Chrome.

**Comment by Sangeeta-Shrivas** [comment]
Leethub not working. no new uploads

**Comment by floatingnahid22** [comment]
> It wasn't just about me. I'm having the same problem. I'm using M1 and Chrome.

I solved this problem by going back to  old version of LeetCode.

**Comment by LOVKUSH9888** [comment]
> > It wasn't just about me. I'm having the same problem. I'm using M1 and Chrome.
> 
> I solved this problem by going back to old version of LeetCode.

How you back to the older version?

**Comment by marknagy14** [comment]
> 

at the dropbox of your account from the right upper corner, you will find revert to older version.

**Comment by being-nitin** [comment]
I solved this problem by going back to the older version of leetcode

**Comment by ani280919** [comment]
I went back to the previous version -> could successfully commit to github the problem-> but again the same issue has been raised!

**Comment by jai-bhardwaj** [comment]
I'm unable to upload my solutions to my GitHub repository. please help!

**Comment by shreyashpandey** [comment]
leethub not working, please help, no submissions working

**Comment by DeeLaw-01** [comment]
For anyone that it isn't working for. When you are done with your code on leetcode:

- Click on your profile picture icon.
- Click on "Revert to old version".
- Your code will persist onto the old version.
- Click "Submit".
- You're done! It should work!

You can always go back to the newer version once you're done with the submission. Hope this helps!
